global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10m
remote_write:
- url: "http://192.168.10.125:18081/prometheus"
  write_relabel_configs:
  - source_labels: [__name__]
    action: keep
    regex: go_gc_cycles_automatic_gc_cycles_total
  remote_timeout: 30s
scrape_configs:
  # prometheus
  - job_name: prometheus
    static_configs:
      - targets: ['192.168.10.125:19090']
        labels:
          instance: prometheus

  # 采集node exporter监控数据，即linux
  - job_name: linux
    static_configs:
      - targets: ['192.168.10.125:19100']
        labels:
          instance: localhost
