version: "3.3"
services:
  rabbit1:
    image: rabbitmq:3-management
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit1
    depends_on:
      - rabbit3
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    configs:
      - source: rabbitmq_config
        target: /etc/rabbitmq/rabbitmq.config
      - source: definitons_json
        target: /etc/rabbitmq/definitions.json
    networks:
      - rabbitmq-cluster
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == worker
          - node.hostname == worker1   
  rabbit2:
    image: rabbitmq:3-management
    hostname: rabbit2
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit2
    depends_on:
      - rabbit3
    configs:
      - source: rabbitmq_config
        target: /etc/rabbitmq/rabbitmq.config
      - source: definitons_json
        target: /etc/rabbitmq/definitions.json
    networks:
      - rabbitmq-cluster
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == worker
          - node.hostname == worker2  
  rabbit3:
    image: rabbitmq:3-management
    hostname: rabbit3
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit3
    configs:
      - source: rabbitmq_config
        target: /etc/rabbitmq/rabbitmq.config
      - source: definitons_json
        target: /etc/rabbitmq/definitions.json
    networks:
      - rabbitmq-cluster
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == worker 
          - node.hostname == worker3 

configs:
  rabbitmq_config:
    file: rabbitmq.config
  definitons_json:
    file: definitions.json

networks:
  rabbitmq-cluster:
    external: true